//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace GFTTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id_Client { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        [DisplayName("Birth Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime Birth_Date { get; set; }
        public int Id_Client_Type { get; set; }
    
        public virtual Client_Type Client_Type { get; set; }
    }
}
