//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace GFTTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Type
    {
        public Client_Type()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int Id_Client_Type { get; set; }

        [DisplayName("Type Client")]
        public string Type_Name { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
    }
}
