//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFTTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GFTTestEntities : DbContext
    {
        public GFTTestEntities()
            : base("name=GFTTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Type> Client_Type { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        public virtual int Delete_Client(Nullable<int> piId_Client, ObjectParameter piCode_Error, ObjectParameter psMsg_Error)
        {
            var piId_ClientParameter = piId_Client.HasValue ?
                new ObjectParameter("piId_Client", piId_Client) :
                new ObjectParameter("piId_Client", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Client", piId_ClientParameter, piCode_Error, psMsg_Error);
        }
    
        public virtual int Insert_Client(string psName, string psEmail, Nullable<System.DateTime> pdBirth_Date, Nullable<int> piId_Client_Type, ObjectParameter piCode_Error, ObjectParameter psMsg_Error)
        {
            var psNameParameter = psName != null ?
                new ObjectParameter("psName", psName) :
                new ObjectParameter("psName", typeof(string));
    
            var psEmailParameter = psEmail != null ?
                new ObjectParameter("psEmail", psEmail) :
                new ObjectParameter("psEmail", typeof(string));
    
            var pdBirth_DateParameter = pdBirth_Date.HasValue ?
                new ObjectParameter("pdBirth_Date", pdBirth_Date) :
                new ObjectParameter("pdBirth_Date", typeof(System.DateTime));
    
            var piId_Client_TypeParameter = piId_Client_Type.HasValue ?
                new ObjectParameter("piId_Client_Type", piId_Client_Type) :
                new ObjectParameter("piId_Client_Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Client", psNameParameter, psEmailParameter, pdBirth_DateParameter, piId_Client_TypeParameter, piCode_Error, psMsg_Error);
        }
    
        public virtual ObjectResult<Select_Clients_Result> Select_Clients(string psName, Nullable<int> piId_Client_Type, Nullable<int> piId_Column, Nullable<int> piNumber_Rows, Nullable<int> piNumber_Page, ObjectParameter piCode_Error, ObjectParameter psMsg_Error)
        {
            var psNameParameter = psName != null ?
                new ObjectParameter("psName", psName) :
                new ObjectParameter("psName", typeof(string));
    
            var piId_Client_TypeParameter = piId_Client_Type.HasValue ?
                new ObjectParameter("piId_Client_Type", piId_Client_Type) :
                new ObjectParameter("piId_Client_Type", typeof(int));
    
            var piId_ColumnParameter = piId_Column.HasValue ?
                new ObjectParameter("piId_Column", piId_Column) :
                new ObjectParameter("piId_Column", typeof(int));
    
            var piNumber_RowsParameter = piNumber_Rows.HasValue ?
                new ObjectParameter("piNumber_Rows", piNumber_Rows) :
                new ObjectParameter("piNumber_Rows", typeof(int));
    
            var piNumber_PageParameter = piNumber_Page.HasValue ?
                new ObjectParameter("piNumber_Page", piNumber_Page) :
                new ObjectParameter("piNumber_Page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Clients_Result>("Select_Clients", psNameParameter, piId_Client_TypeParameter, piId_ColumnParameter, piNumber_RowsParameter, piNumber_PageParameter, piCode_Error, psMsg_Error);
        }
    
        public virtual int Update_Client(Nullable<int> piId_Client, string psName, string psEmail, Nullable<System.DateTime> pdBirth_Date, Nullable<int> piId_Client_Type, ObjectParameter piCode_Error, ObjectParameter psMsg_Error)
        {
            var piId_ClientParameter = piId_Client.HasValue ?
                new ObjectParameter("piId_Client", piId_Client) :
                new ObjectParameter("piId_Client", typeof(int));
    
            var psNameParameter = psName != null ?
                new ObjectParameter("psName", psName) :
                new ObjectParameter("psName", typeof(string));
    
            var psEmailParameter = psEmail != null ?
                new ObjectParameter("psEmail", psEmail) :
                new ObjectParameter("psEmail", typeof(string));
    
            var pdBirth_DateParameter = pdBirth_Date.HasValue ?
                new ObjectParameter("pdBirth_Date", pdBirth_Date) :
                new ObjectParameter("pdBirth_Date", typeof(System.DateTime));
    
            var piId_Client_TypeParameter = piId_Client_Type.HasValue ?
                new ObjectParameter("piId_Client_Type", piId_Client_Type) :
                new ObjectParameter("piId_Client_Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Client", piId_ClientParameter, psNameParameter, psEmailParameter, pdBirth_DateParameter, piId_Client_TypeParameter, piCode_Error, psMsg_Error);
        }
    }
}
